name: Build APK (Auto Care)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Instalar dependências
        run: flutter pub get

      - name: Construir APK (release)
        run: flutter build apk --release

      - name: Publicar
